const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
global.crypto=require('node:crypto').webcrypto;
vm.runInThisContext(fs.readFileSync('supplements.js','utf8'));
const base={topics:[{id:'t',title:'Literature',categories:[]}],pages:[{id:'old',title:'Book',topic:'t',kind:'quick',updated:1,blocks:[{id:'note',type:'text',text:'My own note'}]}]};
const source={id:'s',title:'Book',topic:'t',updated:2,blocks:[{id:'cover',type:'image',image:'im',text:'Cover',layout:'narrow'},{id:'essay',type:'text',text:'New analysis'}]};
const pack={supplement:{version:2,id:'pack',operations:[{pageId:'s',mode:'append',createIfMissing:true,matchIds:['old'],matchTitles:['Book']}]},library:{topics:base.topics,pages:[source]},images:{im:'data:image/png;base64,aA=='}};
const snapshot=JSON.stringify(base),plan=planSupplement(base,pack);
assert.equal(JSON.stringify(base),snapshot);
assert.equal(plan.added,0);assert.equal(plan.updated,1);
assert.equal(plan.library.pages[0].kind,'quick');
assert.deepEqual(plan.library.pages[0].blocks[1],base.pages[0].blocks[0]);
assert.equal(Object.values(plan.images)[0],pack.images.im);
const repeated=planSupplement(plan.library,pack);
assert.equal(repeated.added,0);assert.equal(repeated.updated,0);assert.equal(repeated.skipped,1);
assert.deepEqual(repeated.library,plan.library);assert.deepEqual(repeated.images,{});
const coverPack=structuredClone(pack);coverPack.supplement.operations[0].mode='cover';coverPack.supplement.operations[0].createIfMissing=false;
coverPack.library.pages[0].blocks=[source.blocks[0],{id:'link',type:'link',text:'Cover source',url:'https://example.com'}];
const covered=planSupplement(base,coverPack);
assert.deepEqual(covered.library.pages[0].blocks.filter(b=>b.type==='text'),base.pages[0].blocks);
assert.throws(()=>planSupplement({...base,pages:[]},coverPack),/introuvable/);
assert.throws(()=>planSupplement({...base,pages:[...base.pages,{...base.pages[0],id:'duplicate'}]},pack),/Plusieurs/);
const invalid=structuredClone(coverPack);invalid.library.pages[0].blocks.push({id:'bad',type:'text',text:'Unwanted replacement'});
assert.throws(()=>planSupplement(base,invalid),/couverture seule/);
const fresh=planSupplement({...base,pages:[]},pack);assert.equal(fresh.added,1);assert.equal(fresh.updated,0);
assert.equal(planSupplement(fresh.library,pack).added,0);
const renamed=structuredClone(base);renamed.pages[0].title='Renamed personal title';
assert.equal(planSupplement(renamed,pack).updated,1);
assert.equal(planSupplement(renamed,pack).library.pages[0].title,'Renamed personal title');
const imported=structuredClone(base);imported.pages[0].id='id-changed-by-legacy-import';
assert.equal(planSupplement(imported,pack).updated,1);
const dupOps=structuredClone(pack);dupOps.supplement.operations.push(dupOps.supplement.operations[0]);
assert.throws(()=>planSupplement(base,dupOps),/invalide/);
console.log('PASS: additive updates, cover-only preservation, repeat import, legacy IDs, renamed title, ambiguous/missing targets, invalid operations.');
